name: CICD Non-admin 1

on:
  push:
    branches:
      - dev

env:
  AWS_REGION: us-east-1
  REPO_ADMIN_USER_NAME_PARAMETER: AP_GH_REPOS_ADMIN_USER_NAME 
  REPO_ADMIN_USER_EMAIL_PARAMETER: AP_GH_REPOS_ADMIN_USER_EMAIL
  SLACK_WEBHOOK_URL_PARAMETER: AP_SLACK_GHA_NOTIFY_BOT_INCOMING_WEBHOOK_URL

jobs:
  cicd-non-admin-1:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'ronfontebo' }}
    steps:
      - name: Checkout Repo
        id: checkout-repo
        uses: actions/checkout@v4

      - name: Get Commit Author
        id: get-commit-author
        if: ${{ steps.checkout-repo.outcome == 'success' }}        
        run: |
          echo "COMMIT_AUTHOR=$(echo \"${{ github.event.head_commit.author.name }}\")" >> $GITHUB_ENV

      - name: Get Commit Message
        id: get-commit-message
        if: ${{ steps.get-commit-author.outcome == 'success' }}    
        run: |
          echo "COMMIT_MESSAGE=$(echo \"${{ github.event.head_commit.message }}\")" >> $GITHUB_ENV

      - name: Open PR
        id: open-pr
        if: ${{ steps.get-commit-message.outcome == 'success' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --head "dev" \
            --base "main" \
            --title ${{ env.COMMIT_MESSAGE }} \
            --body ${{ env.COMMIT_MESSAGE }} > /tmp/pr-url.txt

          echo "PR_URL=$(cat /tmp/pr-url.txt)" >> $GITHUB_ENV

      - name: Notify Repo Admin Success
        id: notify-repo-admin-success
        if: ${{ steps.open-pr.outcome == 'success' }}
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ env.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: |
              New PR:
              PR author: ${{ github.actor }}
              PR URL: ${{ env.PR_URL }}

              @${{ env.SLACK_ADMIN }}, checkout the PR and approve changes for merging.

      - name: Notify Repo Admin Failure
        id: notify-repo-admin-failure
        if: ${{ steps.open-pr.outcome == 'failure' }}
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ env.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: |
              Failed PR:
              @${{ github.actor }}, the PR you tried to open was unsuccessful.
              Revisit your commit, make any necessary changes and recommit.

######################################## APACHEPLAYGROUND™ ########################################